// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorMobCRUD.Models;

namespace SensorMobCRUD.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SensorMobCRUD.Models.Measurment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("hum");

                    b.Property<int>("pm_10");

                    b.Property<int>("pm_1_0");

                    b.Property<int>("pm_2_5");

                    b.Property<int>("sensorId");

                    b.Property<double>("temp");

                    b.Property<DateTime>("time");

                    b.HasKey("Id");

                    b.ToTable("measurments");
                });
#pragma warning restore 612, 618
        }
    }
}
